--local functions
local function config(name)
    return settings.startup['fi_modules_'..name].value
end

local function sprite(name)
    return '__248k-Redux-graphics__/ressources/fission/fi_modules/fi_modules_'..name
end

local limitation_list = {
    'el_train_fuel_diesel',
    'el_grow_energy_crystal',
    'el_cast_pure_iron',
    'el_cast_pure_steel',
    'el_cast_pure_copper',
    'el_cast_pure_aluminum',
    'fi_cast_neodym',
    'fi_cast_glass',
    'fi_cast_gold',
    'fi_cast_titan',
    'el_arc_pure_iron',
    'el_arc_pure_copper',
    'el_arc_pure_aluminum',
    'fi_arc_glass',
    'fi_arc_pure_gold',
    'fi_arc_pure_titan',
    'fi_arc_pure_neodym',
    'fi_compound_material',
    'fi_industrial_steel',
    'fi_GFK',
    'fi_NFK',
    'fu_KFK',
    'fu_TIM',
    'fu_lead_ore',
    'fi_base_crystal',
    'fi_catalyst_crystal',
    'fi_energy_crystal',
    'fi_glass_fiber',
    'fi_natural_fiber',
    'fu_carbon_fiber',
    'fu_tech_sign',
    'gr_pcb',
    'gr_gold_wire',
    'gr_circuit',
    'gr_stack_up',
    'gr_stack_down',
    'fi_empty_solution',
    --'fi_extract_rich_powder',
    'fi_strong_acid',
    'fi_refinery_basic',
    'fi_refinery_coal',
    'fi_refinery_sulfur',
    'fi_refinery_kerosene_coal',
    'fi_refinery_kerosene',
    'fi_empty_solution',
    'fu_gold_ingot',
    'fu_titan_ingot',
    'fu_neodym_ingot',
    'fu_lead_ingot',
    'fu_gold_plate',
    'fu_titan_plate',
    'fu_neodym_plate',
    'fu_lead_plate',

}

--item
data:extend({
    {
        name = 'fi_modules_productivity_1',
        type = 'module',
        icon = sprite('productivity_1.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fi_item_subgroup_j',
        category = '248k_productivity_category',
        tier = 1,
        order = 'a-a',
        weight = 20 * kg,
        effect = {
            consumption = 0.9,--{bonus = 0.9},
            speed = -0.2, --{bonus = -0.2},
            productivity = 0.06, --{bonus = 0.06},
            pollution = 0.3, --{bonus = 0.3}
        },
        limitation = limitation_list,
        limitation_message_key = 'limitation_message',
    },
    {
        name = 'fi_modules_productivity_2',
        type = 'module',
        icon = sprite('productivity_2.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fi_item_subgroup_j',
        category = '248k_productivity_category',
        tier = 2,
        order = 'a-a',
        weight = 20 * kg,
        effect = {
            consumption = 1.4, --{bonus = 1.4},
            speed = -0.35, --{bonus = -0.35},
            productivity = 0.10, --{bonus = 0.10},
            pollution = 0.6, --{bonus = 0.6}
        },
        limitation = limitation_list,
        limitation_message_key = 'limitation_message',
    },
    {
        name = 'fi_modules_productivity_3',
        type = 'module',
        icon = sprite('productivity_3.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fi_item_subgroup_j',
        category = '248k_productivity_category',
        tier = 3,
        order = 'a-a',
        weight = 20 * kg,
        effect = {
            consumption = 2.6, --{bonus = 2.6},
            speed = -0.6, --{bonus = -0.6},
            productivity = 0.12, --{bonus = 0.12},
            pollution = 0.9, --{bonus = 0.9}
        },
        limitation = limitation_list,
        limitation_message_key = 'limitation_message',
    },
    {
        name = 'fi_modules_productivity_4',
        type = 'module',
        icon = sprite('productivity_4.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'gr_item_subgroup_d',
        category = '248k_productivity_category',
        tier = 4,
        order = 'a-a',
        weight = 20 * kg,
        effect = {
            consumption = 2, --{bonus = 2},
            speed = -0.5, --{bonus = -0.5},
            productivity = 0.05, --{bonus = 0.05},
            pollution = 1, --{bonus = 1}
        },
    },
    {
        name = 'fi_modules_productivity_5',
        type = 'module',
        icon = sprite('productivity_5.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'gr_item_subgroup_d',
        category = '248k_productivity_category',
        tier = 5,
        order = 'a-b',
        weight = 20 * kg,
        effect = {
            consumption = 3, --{bonus = 3},
            speed = -0.7, --{bonus = -0.7},
            productivity = 0.1, --{bonus = 0.1},
            pollution = 1, --{bonus = 1}
        },
    },
    {
        name = 'fi_modules_productivity_6',
        type = 'module',
        icon = sprite('productivity_6.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'gr_item_subgroup_d',
        category = '248k_productivity_category',
        tier = 6,
        order = 'a-c',
        weight = 20 * kg,
        effect = {
            consumption = 6, --{bonus = 6},
            speed = -0.9, --{bonus = -0.9},
            productivity = 0.25, --{bonus = 0.25},
            pollution = 1, --{bonus = 1}
        },
    },
    {
        name = 'fi_modules_base',
        type = 'item',
        icon = sprite('base.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fi_item_subgroup_e',
        order = 'b-k',
        weight = 10 * kg,
    },
    {
        name = 'fi_modules_core',
        type = 'item',
        icon = sprite('core.png'),
        icon_size = 64,
        stack_size = 100,
        subgroup = 'fi_item_subgroup_e',
        order = 'b-x',
        weight = 10 * kg,
    },
    

})